In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [3]:
df = pd.read_csv("../data/Pakistan Largest Ecommerce Dataset.csv")

C:\Users\HP 850G2\AppData\Local\Temp\ipykernel_2216\4270612918.py:1: DtypeWarning: Columns (0: increment_id) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/Pakistan Largest Ecommerce Dataset.csv")

In [3]:
df.head()

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
0,211131,complete,7/1/2016,kreations_YI 06-L,1950.0,1,1950.0,100147443,Women's Fashion,\N,...,cod,7/1/2016,#REF!,"1,950",2016,7,2016-7,Jul-16,FY17,1.0
1,211133,canceled,7/1/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.0,1,240.0,100147444,Beauty & Grooming,\N,...,cod,7/1/2016,Gross,240,2016,7,2016-7,Jul-16,FY17,2.0
2,211134,canceled,7/1/2016,Ego_UP0017-999-MR0,2450.0,1,2450.0,100147445,Women's Fashion,\N,...,cod,7/1/2016,Gross,"2,450",2016,7,2016-7,Jul-16,FY17,3.0
3,211135,complete,7/1/2016,kcc_krone deal,360.0,1,60.0,100147446,Beauty & Grooming,R-FSD-52352,...,cod,7/1/2016,Net,360,2016,7,2016-7,Jul-16,FY17,4.0
4,211136,order_refunded,7/1/2016,BK7010400AG,555.0,2,1110.0,100147447,Soghaat,\N,...,cod,7/1/2016,Valid,"1,110",2016,7,2016-7,Jul-16,FY17,5.0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 584524 entries, 0 to 584523
Data columns (total 21 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   item_id                584524 non-null  int64
 1   status                 584509 non-null  str
 2   created_at             584524 non-null  str
 3   sku                    584504 non-null  str
 4   price                  584524 non-null  float64
 5   qty_ordered            584524 non-null  int64
 6   grand_total            584524 non-null  float64
 7   increment_id           584524 non-null  object
 8   category_name_1        584360 non-null  str
 9   sales_commission_code  447346 non-null  str
 10  discount_amount        584524 non-null  float64
 11  payment_method         584524 non-null  str
 12  Working Date           584524 non-null  str
 13  BI Status              584524 non-null  str
 14  MV                     584524 non-null  str
 15  Year                   584524 non-null  int64
 16  Month                  584524 non-null  int64
 17  Customer Since         584513 non-null  str
 18  M-Y                    584524 non-null  str
 19  FY                     584524 non-null  str
 20  Customer ID            584513 non-null  float64
dtypes: float64(4), int64(4), object(1), str(12)
memory usage: 93.7+ MB

In [5]:
df.isnull().sum()

item_id                       0
status                       15
created_at                    0
sku                          20
price                         0
qty_ordered                   0
grand_total                   0
increment_id                  0
category_name_1             164
sales_commission_code    137178
discount_amount               0
payment_method                0
Working Date                  0
BI Status                     0
MV                            0
Year                          0
Month                         0
Customer Since               11
M-Y                           0
FY                            0
Customer ID                  11
dtype: int64

In [6]:
df = df.drop(columns=['sales_commission_code'])

In [7]:
df.shape

(584524, 20)

In [8]:
df.head()

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,discount_amount,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
0,211131,complete,7/1/2016,kreations_YI 06-L,1950.0,1,1950.0,100147443,Women's Fashion,0.0,cod,7/1/2016,#REF!,"1,950",2016,7,2016-7,Jul-16,FY17,1.0
1,211133,canceled,7/1/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.0,1,240.0,100147444,Beauty & Grooming,0.0,cod,7/1/2016,Gross,240,2016,7,2016-7,Jul-16,FY17,2.0
2,211134,canceled,7/1/2016,Ego_UP0017-999-MR0,2450.0,1,2450.0,100147445,Women's Fashion,0.0,cod,7/1/2016,Gross,"2,450",2016,7,2016-7,Jul-16,FY17,3.0
3,211135,complete,7/1/2016,kcc_krone deal,360.0,1,60.0,100147446,Beauty & Grooming,300.0,cod,7/1/2016,Net,360,2016,7,2016-7,Jul-16,FY17,4.0
4,211136,order_refunded,7/1/2016,BK7010400AG,555.0,2,1110.0,100147447,Soghaat,0.0,cod,7/1/2016,Valid,"1,110",2016,7,2016-7,Jul-16,FY17,5.0

In [9]:
df.sku

0                                         kreations_YI 06-L
1         kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...
2                                        Ego_UP0017-999-MR0
3                                            kcc_krone deal
4                                               BK7010400AG
                                ...
584519                                  WOFSCE5AE00357AECDE
584520                                  MATHUA5AF70A7D1E50A
584521                                  MATSAM5B6D7208C6D30
584522                                  MATSAM5B1509B4696EA
584523                                  MATSAM5B10F91A9B6AB
Name: sku, Length: 584524, dtype: str

In [10]:
df["MV"]

0           1,950
1             240
2           2,450
3             360
4           1,110
           ...
584519        699
584520     35,599
584521    259,998
584522    174,600
584523    217,280
Name: MV, Length: 584524, dtype: str

In [11]:
df["item_id"].duplicated().sum()

np.int64(0)

In [12]:
df.dropna(subset=['Customer ID', 'sku', 'status', 'category_name_1', 'Customer Since'], inplace=True)

In [13]:
df

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,discount_amount,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
0,211131,complete,7/1/2016,kreations_YI 06-L,1950.0,1,1950.0,100147443,Women's Fashion,0.0,cod,7/1/2016,#REF!,"1,950",2016,7,2016-7,Jul-16,FY17,1.0
1,211133,canceled,7/1/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.0,1,240.0,100147444,Beauty & Grooming,0.0,cod,7/1/2016,Gross,240,2016,7,2016-7,Jul-16,FY17,2.0
2,211134,canceled,7/1/2016,Ego_UP0017-999-MR0,2450.0,1,2450.0,100147445,Women's Fashion,0.0,cod,7/1/2016,Gross,"2,450",2016,7,2016-7,Jul-16,FY17,3.0
3,211135,complete,7/1/2016,kcc_krone deal,360.0,1,60.0,100147446,Beauty & Grooming,300.0,cod,7/1/2016,Net,360,2016,7,2016-7,Jul-16,FY17,4.0
4,211136,order_refunded,7/1/2016,BK7010400AG,555.0,2,1110.0,100147447,Soghaat,0.0,cod,7/1/2016,Valid,"1,110",2016,7,2016-7,Jul-16,FY17,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584519,905204,cod,8/28/2018,WOFSCE5AE00357AECDE,699.0,1,849.0,100562385,Women's Fashion,0.0,cod,8/28/2018,Valid,699,2018,8,2018-8,Aug-18,FY19,115320.0
584520,905205,processing,8/28/2018,MATHUA5AF70A7D1E50A,35599.0,1,35899.0,100562386,Mobiles & Tablets,0.0,bankalfalah,8/28/2018,Gross,"35,599",2018,8,2018-8,Aug-18,FY19,115326.0
584521,905206,processing,8/28/2018,MATSAM5B6D7208C6D30,129999.0,2,652178.0,100562387,Mobiles & Tablets,0.0,bankalfalah,8/28/2018,Gross,"259,998",2018,8,2018-7,Aug-18,FY19,113474.0
584522,905207,processing,8/28/2018,MATSAM5B1509B4696EA,87300.0,2,652178.0,100562387,Mobiles & Tablets,0.0,bankalfalah,8/28/2018,Gross,"174,600",2018,8,2018-7,Aug-18,FY19,113474.0
584523,905208,processing,8/28/2018,MATSAM5B10F91A9B6AB,108640.0,2,652178.0,100562387,Mobiles & Tablets,0.0,bankalfalah,8/28/2018,Gross,"217,280",2018,8,2018-7,Aug-18,FY19,113474.0

In [14]:
df.shape

(584314, 20)

In [15]:
df.isnull().sum()

item_id            0
status             0
created_at         0
sku                0
price              0
qty_ordered        0
grand_total        0
increment_id       0
category_name_1    0
discount_amount    0
payment_method     0
Working Date       0
BI Status          0
MV                 0
Year               0
Month              0
Customer Since     0
M-Y                0
FY                 0
Customer ID        0
dtype: int64

In [16]:
# remove grand_total, discout amount -ve values

df = df[df['discount_amount'] >= 0]

In [17]:
df = df[df['grand_total'] >= 0]

In [18]:
df.shape

(584235, 20)

In [19]:
df.status.value_counts()

status
complete          233657
canceled          201107
received           77274
order_refunded     59494
refund              8002
cod                 2854
paid                1159
closed               494
payment_review        57
pending               48
processing            33
holded                31
fraud                 10
pending_paypal         7
exchange               4
\N                     4
Name: count, dtype: int64

In [20]:
df.category_name_1.value_counts()

category_name_1
Mobiles & Tablets     115700
Men's Fashion          92214
Women's Fashion        59716
Appliances             52404
Superstore             43596
Beauty & Grooming      41488
Soghaat                34002
Others                 29208
Home & Living          26502
Entertainment          26317
Health & Sports        17498
Kids & Baby            16488
Computing              15930
\N                      7832
School & Education      3470
Books                   1870
Name: count, dtype: int64

In [21]:
df.payment_method.value_counts()

payment_method
cod                  271770
Payaxis               97616
Easypay               82854
jazzwallet            35145
easypay_voucher       31175
bankalfalah           23041
jazzvoucher           15633
Easypay_MA            14026
customercredit         7554
apg                    1758
ublcreditcard           882
cashatdoorstep          732
mcblite                 723
mygateway               669
internetbanking         472
productcredit           125
marketingexpense         45
financesettlement        15
Name: count, dtype: int64

In [22]:
df['BI Status'].value_counts()

BI Status
Net      234150
Gross    201297
Valid    148787
#REF!         1
Name: count, dtype: int64

In [23]:
df.grand_total.value_counts()

grand_total
0.0        9616
1000.0     5145
2000.0     3780
2500.0     3235
5000.0     2912
           ...
7816.0        1
2311.0        1
27280.0       1
28599.0       1
23510.0       1
Name: count, Length: 36800, dtype: int64

In [24]:
df.isnull().sum()

item_id            0
status             0
created_at         0
sku                0
price              0
qty_ordered        0
grand_total        0
increment_id       0
category_name_1    0
discount_amount    0
payment_method     0
Working Date       0
BI Status          0
MV                 0
Year               0
Month              0
Customer Since     0
M-Y                0
FY                 0
Customer ID        0
dtype: int64

In [25]:
col_list = df.columns
col_list

Index(['item_id', 'status', 'created_at', 'sku', 'price', 'qty_ordered',
       'grand_total', 'increment_id', 'category_name_1', 'discount_amount',
       'payment_method', 'Working Date', 'BI Status', 'MV', 'Year', 'Month',
       'Customer Since', 'M-Y', 'FY', 'Customer ID'],
      dtype='str')

In [26]:
for i in col_list:
    print(f"{i}:",len(df[df[f"{i}"] == '\\N']))

item_id: 0
status: 4
created_at: 0
sku: 0
price: 0
qty_ordered: 0
grand_total: 0
increment_id: 0
category_name_1: 7832
discount_amount: 0
payment_method: 0
Working Date: 0
BI Status: 0
MV: 0
Year: 0
Month: 0
Customer Since: 0
M-Y: 0
FY: 0
Customer ID: 0

In [27]:
df = df[df['status'] != '\\N']

In [28]:
df.shape

(584231, 20)

In [29]:
df['category_name_1'] = df['category_name_1'].replace('\\N', 'Unknown')

In [30]:
for i in col_list:
    print(f"{i}:",len(df[df[f"{i}"] == '\\N']))

item_id: 0
status: 0
created_at: 0
sku: 0
price: 0
qty_ordered: 0
grand_total: 0
increment_id: 0
category_name_1: 0
discount_amount: 0
payment_method: 0
Working Date: 0
BI Status: 0
MV: 0
Year: 0
Month: 0
Customer Since: 0
M-Y: 0
FY: 0
Customer ID: 0

In [31]:
df.shape

(584231, 20)

In [32]:
df['status'] = df['status'].replace(['complete', 'received', 'paid', 'cod', 'closed'], 'completed')

In [33]:
df['status'] = df['status'].replace(['refund', 'order_refunded'], 'refunded')

In [34]:
df['status'] = df['status'].replace(['pending','processing','payment_review','pending_paypal', 'holded'], 'pending')

In [35]:
df.status.value_counts()

status
completed    315438
canceled     201107
refunded      67496
pending         176
fraud            10
exchange          4
Name: count, dtype: int64

In [36]:
df

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,discount_amount,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
0,211131,completed,7/1/2016,kreations_YI 06-L,1950.0,1,1950.0,100147443,Women's Fashion,0.0,cod,7/1/2016,#REF!,"1,950",2016,7,2016-7,Jul-16,FY17,1.0
1,211133,canceled,7/1/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.0,1,240.0,100147444,Beauty & Grooming,0.0,cod,7/1/2016,Gross,240,2016,7,2016-7,Jul-16,FY17,2.0
2,211134,canceled,7/1/2016,Ego_UP0017-999-MR0,2450.0,1,2450.0,100147445,Women's Fashion,0.0,cod,7/1/2016,Gross,"2,450",2016,7,2016-7,Jul-16,FY17,3.0
3,211135,completed,7/1/2016,kcc_krone deal,360.0,1,60.0,100147446,Beauty & Grooming,300.0,cod,7/1/2016,Net,360,2016,7,2016-7,Jul-16,FY17,4.0
4,211136,refunded,7/1/2016,BK7010400AG,555.0,2,1110.0,100147447,Soghaat,0.0,cod,7/1/2016,Valid,"1,110",2016,7,2016-7,Jul-16,FY17,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584519,905204,completed,8/28/2018,WOFSCE5AE00357AECDE,699.0,1,849.0,100562385,Women's Fashion,0.0,cod,8/28/2018,Valid,699,2018,8,2018-8,Aug-18,FY19,115320.0
584520,905205,pending,8/28/2018,MATHUA5AF70A7D1E50A,35599.0,1,35899.0,100562386,Mobiles & Tablets,0.0,bankalfalah,8/28/2018,Gross,"35,599",2018,8,2018-8,Aug-18,FY19,115326.0
584521,905206,pending,8/28/2018,MATSAM5B6D7208C6D30,129999.0,2,652178.0,100562387,Mobiles & Tablets,0.0,bankalfalah,8/28/2018,Gross,"259,998",2018,8,2018-7,Aug-18,FY19,113474.0
584522,905207,pending,8/28/2018,MATSAM5B1509B4696EA,87300.0,2,652178.0,100562387,Mobiles & Tablets,0.0,bankalfalah,8/28/2018,Gross,"174,600",2018,8,2018-7,Aug-18,FY19,113474.0
584523,905208,pending,8/28/2018,MATSAM5B10F91A9B6AB,108640.0,2,652178.0,100562387,Mobiles & Tablets,0.0,bankalfalah,8/28/2018,Gross,"217,280",2018,8,2018-7,Aug-18,FY19,113474.0

In [37]:
df.columns

Index(['item_id', 'status', 'created_at', 'sku', 'price', 'qty_ordered',
       'grand_total', 'increment_id', 'category_name_1', 'discount_amount',
       'payment_method', 'Working Date', 'BI Status', 'MV', 'Year', 'Month',
       'Customer Since', 'M-Y', 'FY', 'Customer ID'],
      dtype='str')

In [4]:
df.to_csv('../data/pakistan_larget_ecommerce_clean_dataset.csv', index=False)

In [38]:
df['grand_total'].sum()

np.float64(4985899510.0965)

In [39]:
df['category_name_1'].value_counts()

category_name_1
Mobiles & Tablets     115700
Men's Fashion          92214
Women's Fashion        59716
Appliances             52404
Superstore             43596
Beauty & Grooming      41488
Soghaat                34002
Others                 29208
Home & Living          26502
Entertainment          26317
Health & Sports        17498
Kids & Baby            16488
Computing              15930
Unknown                 7828
School & Education      3470
Books                   1870
Name: count, dtype: int64

In [40]:
df[df['category_name_1'] == 'Unknown']

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,discount_amount,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
24,211157,refunded,7/1/2016,D Lend a Helping Hand,1000.0,1,0.0,100147461,Unknown,0.0,customercredit,7/1/2016,Valid,"1,000",2016,7,2016-7,Jul-16,FY17,16.0
72,211214,canceled,7/1/2016,sentiments_WRK1612,1.0,1,1.0,100147496,Unknown,0.0,cod,7/1/2016,Gross,1,2016,7,2016-7,Jul-16,FY17,33.0
79,211222,canceled,7/1/2016,sentiments_WRK1612,1.0,5,5.0,100147502,Unknown,0.0,cod,7/1/2016,Gross,5,2016,7,2016-7,Jul-16,FY17,33.0
80,211223,canceled,7/1/2016,sentiments_WRK1612,1.0,2,2.0,100147503,Unknown,0.0,cod,7/1/2016,Gross,2,2016,7,2016-7,Jul-16,FY17,33.0
81,211225,canceled,7/1/2016,sentiments_WRK1612,1.0,1,1.0,100147505,Unknown,0.0,cod,7/1/2016,Gross,1,2016,7,2016-7,Jul-16,FY17,33.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423207,722206,refunded,12/27/2017,OTHOTH5A0945D0A72F4,90.0,2,330.0,100440581,Unknown,0.0,cod,12/27/2017,Valid,180,2017,12,2017-11,Dec-17,FY18,66884.0
423231,722242,completed,12/27/2017,MEFQMO59B0942707B79-L,99.0,1,249.0,100440593,Unknown,0.0,cod,12/27/2017,Valid,99,2017,12,2017-11,Dec-17,FY18,66884.0
423826,722915,refunded,12/29/2017,OTHOTH5A0945D0A72F4,90.0,2,330.0,100440967,Unknown,0.0,cod,12/29/2017,Valid,180,2017,12,2017-8,Dec-17,FY18,59587.0
423829,722918,refunded,12/29/2017,MEFQMO59B0942707B79-S,99.0,2,348.0,100440970,Unknown,0.0,cod,12/29/2017,Valid,198,2017,12,2017-11,Dec-17,FY18,66884.0
423830,722920,completed,12/29/2017,MEFQMO59B0942707B79-L,99.0,2,348.0,100440971,Unknown,0.0,cod,12/29/2017,Valid,198,2017,12,2017-8,Dec-17,FY18,59587.0

In [41]:
df

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,discount_amount,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
0,211131,completed,7/1/2016,kreations_YI 06-L,1950.0,1,1950.0,100147443,Women's Fashion,0.0,cod,7/1/2016,#REF!,"1,950",2016,7,2016-7,Jul-16,FY17,1.0
1,211133,canceled,7/1/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.0,1,240.0,100147444,Beauty & Grooming,0.0,cod,7/1/2016,Gross,240,2016,7,2016-7,Jul-16,FY17,2.0
2,211134,canceled,7/1/2016,Ego_UP0017-999-MR0,2450.0,1,2450.0,100147445,Women's Fashion,0.0,cod,7/1/2016,Gross,"2,450",2016,7,2016-7,Jul-16,FY17,3.0
3,211135,completed,7/1/2016,kcc_krone deal,360.0,1,60.0,100147446,Beauty & Grooming,300.0,cod,7/1/2016,Net,360,2016,7,2016-7,Jul-16,FY17,4.0
4,211136,refunded,7/1/2016,BK7010400AG,555.0,2,1110.0,100147447,Soghaat,0.0,cod,7/1/2016,Valid,"1,110",2016,7,2016-7,Jul-16,FY17,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584519,905204,completed,8/28/2018,WOFSCE5AE00357AECDE,699.0,1,849.0,100562385,Women's Fashion,0.0,cod,8/28/2018,Valid,699,2018,8,2018-8,Aug-18,FY19,115320.0
584520,905205,pending,8/28/2018,MATHUA5AF70A7D1E50A,35599.0,1,35899.0,100562386,Mobiles & Tablets,0.0,bankalfalah,8/28/2018,Gross,"35,599",2018,8,2018-8,Aug-18,FY19,115326.0
584521,905206,pending,8/28/2018,MATSAM5B6D7208C6D30,129999.0,2,652178.0,100562387,Mobiles & Tablets,0.0,bankalfalah,8/28/2018,Gross,"259,998",2018,8,2018-7,Aug-18,FY19,113474.0
584522,905207,pending,8/28/2018,MATSAM5B1509B4696EA,87300.0,2,652178.0,100562387,Mobiles & Tablets,0.0,bankalfalah,8/28/2018,Gross,"174,600",2018,8,2018-7,Aug-18,FY19,113474.0
584523,905208,pending,8/28/2018,MATSAM5B10F91A9B6AB,108640.0,2,652178.0,100562387,Mobiles & Tablets,0.0,bankalfalah,8/28/2018,Gross,"217,280",2018,8,2018-7,Aug-18,FY19,113474.0

In [42]:
df['payment_method'].value_counts()

payment_method
cod                  271766
Payaxis               97616
Easypay               82854
jazzwallet            35145
easypay_voucher       31175
bankalfalah           23041
jazzvoucher           15633
Easypay_MA            14026
customercredit         7554
apg                    1758
ublcreditcard           882
cashatdoorstep          732
mcblite                 723
mygateway               669
internetbanking         472
productcredit           125
marketingexpense         45
financesettlement        15
Name: count, dtype: int64

In [45]:
df['BI Status'].value_counts()

BI Status
Net      234150
Gross    201293
Valid    148787
#REF!         1
Name: count, dtype: int64

In [2]:
df = pd.read_csv("../data/pakistan_larget_ecommerce_clean_dataset.csv")

df['sku']

C:\Users\HP 850G2\AppData\Local\Temp\ipykernel_6272\49245749.py:1: DtypeWarning: Columns (0: increment_id) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/pakistan_larget_ecommerce_clean_dataset.csv")

0                                         kreations_YI 06-L
1         kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...
2                                        Ego_UP0017-999-MR0
3                                            kcc_krone deal
4                                               BK7010400AG
                                ...
584226                                  WOFSCE5AE00357AECDE
584227                                  MATHUA5AF70A7D1E50A
584228                                  MATSAM5B6D7208C6D30
584229                                  MATSAM5B1509B4696EA
584230                                  MATSAM5B10F91A9B6AB
Name: sku, Length: 584231, dtype: str

In [9]:
mv = df[df['price'] <= 0]

In [10]:
mv['MV']

6598       -
6603       -
7004       -
8298       -
8333       -
          ...
583967     -
583968     -
583971     -
583977     -
583978     -
Name: MV, Length: 2214, dtype: str

In [11]:
mv

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,discount_amount,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
6598,218538,canceled,7/26/2016,"west point_Deluxe Juicer, Blender & Grinder - ...",0.0,1,0.0,100152813,Appliances,0.0,cod,7/26/2016,Gross,-,2016,7,2016-7,Jul-16,FY17,1961.0
6603,218542,canceled,7/26/2016,"west point_Deluxe Juicer, Blender & Grinder - ...",0.0,1,0.0,100152817,Appliances,0.0,cod,7/26/2016,Gross,-,2016,7,2016-7,Jul-16,FY17,1962.0
7004,218988,canceled,7/27/2016,"west point_Deluxe Juicer, Blender & Grinder - ...",0.0,1,0.0,100153144,Appliances,0.0,cod,7/27/2016,Gross,-,2016,7,2016-7,Jul-16,FY17,1085.0
8298,220494,canceled,7/29/2016,stinnos_1301,0.0,1,0.0,100154287,Kids & Baby,0.0,cod,7/29/2016,Gross,-,2016,7,2016-7,Jul-16,FY17,2247.0
8333,220540,canceled,7/29/2016,stinnos_1301,0.0,10,0.0,100154316,Kids & Baby,0.0,cod,7/29/2016,Gross,-,2016,7,2016-7,Jul-16,FY17,2257.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583967,904901,completed,8/27/2018,COMTOO59D5164EE7D18,0.0,2,150.0,100562217,Computing,0.0,cod,8/27/2018,Valid,-,2018,8,2018-8,Aug-18,FY19,115277.0
583968,904902,completed,8/27/2018,COMTOO59D5164EE7D18,0.0,2,150.0,100562218,Computing,0.0,cod,8/27/2018,Valid,-,2018,8,2018-8,Aug-18,FY19,115278.0
583971,904906,completed,8/27/2018,COMTOO59D5164EE7D18,0.0,2,150.0,100562220,Computing,0.0,cod,8/27/2018,Valid,-,2018,8,2018-8,Aug-18,FY19,115279.0
583977,904916,completed,8/27/2018,COMTOO59D5164EE7D18,0.0,2,150.0,100562222,Computing,0.0,cod,8/27/2018,Valid,-,2018,8,2018-8,Aug-18,FY19,115281.0
583978,904917,completed,8/27/2018,COMTOO59D5164EE7D18,0.0,1,150.0,100562223,Computing,0.0,cod,8/27/2018,Valid,-,2018,8,2018-8,Aug-18,FY19,115282.0

In [12]:
mv['status'].value_counts()

status
completed    841
canceled     741
refunded     632
Name: count, dtype: int64

In [13]:
mv['sku'].value_counts()

sku
BKSTRA59F192793463E       348
Bahr-e-Shifa              205
BKSTRA59BA5A46D211B       125
Infinix Hot 4-Gold-1       63
BAGPRI5A327299C4F97        51
                         ...
MEFAYB5ACB543D2B29C-L       1
MEFAYB5ACB543D2B29C-XL      1
HASTEC5AF986D02EC8E-XL      1
ENTSON5A449A78B1823         1
APPVIT5A9D2C337C7A5         1
Name: count, Length: 465, dtype: int64

In [15]:
mv[(mv['status'] == 'completed') & (mv['grand_total'] > 0)]

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,discount_amount,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
8358,220568,completed,7/29/2016,stinnos_1301,0.0,2,685.0,100154336,Kids & Baby,0.0,cod,7/29/2016,Net,-,2016,7,2016-7,Jul-16,FY17,1791.0
8771,221032,completed,7/31/2016,stinnos_1301,0.0,1,55.0,100154667,Kids & Baby,0.0,cod,7/31/2016,Net,-,2016,7,2016-7,Jul-16,FY17,607.0
11054,224392,completed,8/5/2016,cr_PEANUT CHIKKIE SPECIAL,0.0,1,70.0,100156701,Soghaat,0.0,cod,8/5/2016,Net,-,2016,8,2016-8,Aug-16,FY17,2875.0
12165,226019,completed,8/8/2016,cr_PEANUT CHIKKIE SPECIAL,0.0,1,70.0,100157647,Soghaat,0.0,cod,8/8/2016,Net,-,2016,8,2016-8,Aug-16,FY17,3184.0
12360,226329,completed,8/8/2016,cr_PEANUT CHIKKIE SPECIAL,0.0,1,155.0,100157822,Soghaat,0.0,cod,8/8/2016,Net,-,2016,8,2016-8,Aug-16,FY17,2875.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583967,904901,completed,8/27/2018,COMTOO59D5164EE7D18,0.0,2,150.0,100562217,Computing,0.0,cod,8/27/2018,Valid,-,2018,8,2018-8,Aug-18,FY19,115277.0
583968,904902,completed,8/27/2018,COMTOO59D5164EE7D18,0.0,2,150.0,100562218,Computing,0.0,cod,8/27/2018,Valid,-,2018,8,2018-8,Aug-18,FY19,115278.0
583971,904906,completed,8/27/2018,COMTOO59D5164EE7D18,0.0,2,150.0,100562220,Computing,0.0,cod,8/27/2018,Valid,-,2018,8,2018-8,Aug-18,FY19,115279.0
583977,904916,completed,8/27/2018,COMTOO59D5164EE7D18,0.0,2,150.0,100562222,Computing,0.0,cod,8/27/2018,Valid,-,2018,8,2018-8,Aug-18,FY19,115281.0
583978,904917,completed,8/27/2018,COMTOO59D5164EE7D18,0.0,1,150.0,100562223,Computing,0.0,cod,8/27/2018,Valid,-,2018,8,2018-8,Aug-18,FY19,115282.0

In [16]:
df['status'].value_counts()

status
completed    315438
canceled     201107
refunded      67496
pending         176
fraud            10
exchange          4
Name: count, dtype: int64

In [22]:
df[(df['price'] > 0) & (df['grand_total'] == 0)]

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,discount_amount,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
14,211146,completed,7/1/2016,kcc_glamour deal,320.0,1,0.0,100147456,Beauty & Grooming,0.0,customercredit,7/1/2016,Net,320,2016,7,2016-7,Jul-16,FY17,12.0
24,211157,refunded,7/1/2016,D Lend a Helping Hand,1000.0,1,0.0,100147461,Unknown,0.0,customercredit,7/1/2016,Valid,"1,000",2016,7,2016-7,Jul-16,FY17,16.0
27,211162,completed,7/1/2016,SKMT_Blood Test,500.0,1,0.0,100147463,Others,0.0,customercredit,7/1/2016,Net,500,2016,7,2016-7,Jul-16,FY17,16.0
28,211163,completed,7/1/2016,SKMT_Medicine,100.0,5,0.0,100147463,Others,0.0,customercredit,7/1/2016,Net,500,2016,7,2016-7,Jul-16,FY17,16.0
266,211422,completed,7/1/2016,sstop_3dcreenwithspeakers,995.0,1,0.0,100147648,Computing,0.0,customercredit,7/1/2016,Net,995,2016,7,2016-7,Jul-16,FY17,87.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583970,904904,completed,8/27/2018,MEFRED5B445E6B94853-S,837.0,1,0.0,100562219,Men's Fashion,0.0,customercredit,8/27/2018,Valid,837,2018,8,2018-3,Aug-18,FY19,93983.0
584075,905028,completed,8/27/2018,ENTECO5A7FE80D6C830,20599.0,1,0.0,100562284,Entertainment,0.0,customercredit,8/27/2018,Valid,"20,599",2018,8,2018-3,Aug-18,FY19,92669.0
584112,905080,completed,8/27/2018,MEFC-T5A79B6E8346D9-M,799.0,1,0.0,100562301,Men's Fashion,0.0,customercredit,8/27/2018,Valid,799,2018,8,2017-11,Aug-18,FY19,76074.0
584221,905196,completed,8/28/2018,MEFGUL5A9F882AA5B99-36,1299.0,1,0.0,100562381,Men's Fashion,0.0,customercredit,8/28/2018,Valid,"1,299",2018,8,2018-6,Aug-18,FY19,111132.0
584222,905198,completed,8/28/2018,MEFPAK5B360B03C6B72,999.0,1,0.0,100562381,Men's Fashion,0.0,customercredit,8/28/2018,Valid,999,2018,8,2018-6,Aug-18,FY19,111132.0

In [20]:
ch = df[(df['price'] > 0) & (df['grand_total'] == 0)]

In [21]:
ch['BI Status'].value_counts()

BI Status
Net      5112
Valid    4069
Gross     284
Name: count, dtype: int64

In [25]:
ch['status'].value_counts()

status
completed    7406
refunded     1775
canceled      284
Name: count, dtype: int64

In [27]:
ch[ch['MV'] == ch['price']]

Empty DataFrame
Columns: [item_id, status, created_at, sku, price, qty_ordered, grand_total, increment_id, category_name_1, discount_amount, payment_method, Working Date, BI Status, MV, Year, Month, Customer Since, M-Y, FY, Customer ID]
Index: []

In [29]:
gt = df['grand_total'].sum()
mvt = df['MV'].sum()
pt = df['price'].sum()

In [30]:
gt

np.float64(4985899510.0965)

In [33]:
mvt

'1,9502402,4503601,1108036017096,49996,4995,5002101561203201,5504203604908998993201491491,0001,9131,9135005003,00045020,999360165435908503,672908508997,4003,6001432254,5003,1562,99660030093038035042585025136051032530030,41736070045,25024,3002885,5979994,95080536028019993603503507604355213603204357602403601,8757604353603604357603204,2007604355501,23043576076043532032051037023201,4403603202403501,9507954,7507,400320240520520320360360320240320510370360260260803201260260803603603,90013603601,45013603603,950360260260803603603603607603602602608042530019021036026026080350350260260807603603602807602602608036076036036036036032036024035016,460599599360360265903603601203603602609036025036025,9993202403603603,9003603,600360360450360700150143753604503603603601403504505503501,0503,75024554252,67010,7402302302803003007994801,2004,5301,890803702151,3502,4901,6501,8702,0509953602,1603501701702853201,0992407206403,2904803603203603201,6905002,8002,5505709031503603203603603603603603607003607003203503203603203603604801801433603201,06524024099955,8506,50039942,8603603202403,2507753203603202403603202801,6472403603603603203203503603503205121201201203306403301,9503601442853503,2503751801,7251,3305,2001,3501,3503601,3503603608,1503603603601,4992,2503608,1508,3009,4903603603603603603204283608603003603603601,765320320320320320320240320320240809991,56050019935052024,4997005401,0203509992,5082,5081,9001401441,1991,2958008003206403602403202402402402402402402406555,9972402,7502,6952,49937,5502,8801,33568036036049036036051036035040032014088,9997906703202905646,5001,9131,91310065901101803502853,9756396303603202802,9503,0002801,2508993603601201203304353,29545,2153,295435260330809090150801,9806996992502502501,2002401,5301,9992,4002403753759991,7654359991,0502601207996391,0807995,5972151,0501,3153203603202405,9503206302101003,9001,7982,2001,9981491,59815049533,6852602606303505525,9995109996506506506502,9502204,2502,8001,20096,49948,0002,6001,49955,85048,00079555,85048,00080,0004804801,7001,2992,6783,1033,2953,2953,2951,0502,9951,1489991903502809252403701201203703508,76020,10420,5001201441441201803,0701,20032019,37048,0003502501804,5309991,0993,1503,10072,3501,60011,69025,9995102,34032049576060076076064043533021020,89066019094030,2053203201,37530,2055102402,0702,0001,2005856261,6581,2331,1271,1617997992803207751,3754,5301,6473,9753502401,8501,3754,5301,6473,97590804,3801701801709092515015011,1601501,6509592992991,2001501,0902109907002601801,9992603503503506,40090801,1001,6995702402,95032038090759998,4202401201203201801801,3002002353506301,3001504751,950350280998746262,4651,9505708905705101,2506,24065049525,9992003,0501,8706,900150801409,5008016032018030013,999904,38051,9991,0203255101,0993992001001708992,25316,9991,3753505107751,7992403501,6953503403301002851506,2407008991,0997001,6759901,6756,9001,4991605101,0501408001651651202,2992,4003994951,7653994953996,9003503703401603,5001508015028038035020320329,0007,9309253,0701653208006,7005502806,9001,1902,3391,2001,2003,7757,9504,50015010080802606,9003,7501,1903,7754,500260808080150805,9922,4002,4001,1903,7754,500260808080150802,4002,4003601207991,8808203504251443601201203503203503508003,2993,2993201,2001,175994,20038015075808080809068027052028516020080801,019998080805851,1993304251,2002995705106005604354355606504685003701709010012,60035080280801003301,155,9662,6207759999993502805601,1251441,5001449993501,4505106,0002502751,5002,4993201,5001804051651438901,2001,0821,9201506409602805001,92014301001001801,5006252,0006393509009004304803501904252602651501,1903,7754,500260808080150805605101,0904954358993504,7502,9003,00035035035035080804,750905105103802,4001,4001,1252,5502804352801703408017021080585035045020016039580080029912,5008659,40035035024061,4603506951,3503603603506304201901,8253803251,82538012,6001,3521,6001,8253801149969,9991,39935,6403606551801804,5051,3752,9507006,580510350111133036035015007005103991614903996,999149022,8001,5008004806999004252101656,90016522034816920025041,3159803605353502801,89018012036014416536036080801,0509991403507751,3751,2953601801303608017036028016571,99933,685330112103607,5004801,1002,8001,5205702514,5301,0244,5004,8001,4402,9961,2805201,5006,850520114,5001,9501,4998994,0004,4004709201,0004502,0008005101,05010,10010,700753503509993,9001803,9981,9993,8004,6007207201,4003503993402,50045535035035016,5006,9008103002803507196,90013,8951,375150953253601,375165410410141041030070089989937544826013039057033015035025014950040569,9991,5491,7614358004807008603003,60033,0001203601,2405003505,9751951425518218021577038055875110702081952993205701,1759908703301,4996262343601,500607993001,7619001,400400300300435801200144803306,0005,5005,5001,2751,2755,5006,0004,5006,0004,50021,9004652,33819,3701,5001,0503,499100804704609304605509305504604504009201,1004705505506,9003804351,4241,4243,2092,9959991,3003,7503,75020,1047,35032036079932032036036080120120140808012080320180140120801,445289,497999585891435520210908010031,4911,2743503381008992608001,6996995253,9007909997907992,2002,2008605523201,0571,5405358991,2753002506993991,7653,4862,7385123508742602,1008601,2755205203501,9506302801,300981751,0501,9984351,0504358952,2532,3383,2093,750775435520210908010043552021090801003602501202506553,3001,4501,2007991,69511,200801653,7502503,75010,2503,3003,3003,3003,3003,3006,5003993992423272501,0501202,2003501,5981,5003,7896,0008,4201,09916,5006003003902,1501695003201805856,5001,0993795,6258908,7602,4001,3991,1941,065742,2401,0992404,5301,6003601,525225420480840480165180131,6378999991651,4541,6721,9901,95035055287540062553528576073020022518022016925015,85036015,8502,63515,8502,99829,0008007904204804204802404351,6001,4001694401151,2755526996991652,5506,9006,9001503603505121,060599699500480400991,0003985857924001003608994,49033,99999943,8799992,2752,1001,3751,5008991,600759993,86188,99984096,499121,4997408723286205203,900499145,0004,38060,20563,8309991,7658004002,9002,02416,4609991602601206503204,380495510120850325120210210901604253502002,5503,6001,1502,0805006448501,1991956702,5002002103351601601,2804359703253257641906,5004,4904401,8003254001,35080801,9501401,4901201201201561,65869,9993994,5303201,95069,9991,4365,5053001702,4001,790435260425909080100801441755,3751,47568069,99916043526042590908010080144175552,69543526042590908010080144175260180260260804654354253252,3003501,9991,9995,5004,2001,7651,2405007901202401501,7652,9962,9961,76512,1107509233,49910,99933,6851,765120320165140455500800217380300990800435500520330151,54571,99971,9995101,5506406401202501802802808,4206302,5502,5501,68067599930034057043519,5002991,2006,0504296006,3001,9202403603208026525,0606,9001,1951,0501,5254903901206754,3803,7501205999991803504,500802,9962,9964,3803509251503,1609993501509992,5007198753,7503,0008,42024018090280200260804,9006265121568742,9967002103352001,870699260260260280992,9953,0009708508001,26032016,50024024036032036015049995,36029,0003003601,3003506,900350290804,5003507006,3901,4904,3802,6951401,0823,975210355909049529066546540038032540041037524232715113324820,1041,0572,3253,91519,37045,2152,285801,0571,057803504,5303603503791,1061,7007003603603607004957009504,500251553253003303951,499395655210251553253003305993202403602102103604056,9901,1008,4203601,06532034,0004,49530035059999936035012,5301,9501,3521,5004952802254252003305101,05021,5001,6501503603761401401001,490750257036015,8505,9002002994351651,8703602996906902,6002992601,6994,50064,4998,3009,4901,9904105102503,5854006,0557902,0001,6257004,38012049018,5991202405,5001,9906,90099922,8009502203502401,05033816014026033070012,5002342343501,8001,3701401,1003,7751,3133201,3003501,3758401,9501,5609996,9001,5002501807354,5003502,6203503,0001,4993,5003203,5002992,1304251904752803205507003,4992504,0004,0002,20035019,3701,3153601,31518019,37019,3702508633508503601654801,00016516537979980260809253901,45099562,5007,9901208953,4992401,3153209054,0803202,9951201,0001201,4992,9503609993203,9983202,5005140165535360225805991654353603207511,19419,37081099918023,99919,3709,4006305701,37525025032032032010,40011,9006,7503,00019016,9991,09925069959969069062,500802402408080320901,268902605702401,9983604491,99818069015,4501952203151,900190,72572,7003,9982804,5003008996,90024011,90019,3704952406004432092,2505101,1503202402402404,5002403,7502402402401,3752502502509024024036024024024024024024024016024024036039,9996005,5973602402,0505,5006,0001,7654,3804,3802402403201206,95029,590799226,000213,6003,5009992925500195360360229992399222,8002,5503609993604,5309991,1402103508080801002,10026003,0503603201,2751,6251,2001,7002,0001,2533603602,5003509751,9991,9995952,5021,050110100120120360981901,9412,6004454457519,6001,295650505,2001,3752751502201,2008991691,6991,6996154984494491,7491431437464,8959991,050890801,95079972,7001,5981,5982,99551,9991642,9962,9961,8001,5953,4492502502803503257358331,1995702,50029,0007997002,55016,00059,60010,50026026080260260802602608032043443452026080260260808,42036015,2009991206,5501201202401,5003601,0193603208994681,5001906553603601,69515,2001,2302853603603601,3151401,4983993209998,9999,900510105,9993506,999775510105,999510510240105,9994802402403603603603602401,315140140140240105,9992401401401401,500240105,999240224024024024014014014020,9002764222403203201,23034,6001201441001001001001001001001741003503503501,69930,2052,8501,6768,9805002,0005509008003304051,9413996301201201201201201201201201201201201201201201201201209257902502507752501,000800750410902992,5008991,9509251801502401806,5004,9502405,8002003203481742,9955703951,3756996501805,80020,900899675435580580802,6002402402402401,95032016516542018057029989554,0809992,2608742,5005103802901,4901,29915,6005105706402901909955101,1503,3001651,05032067551019,1701,7506255,80032053,06014,2005,8003991002506404902402402402402402402402402402403,0502402402402402404952,5202,5201,4402,4902,1009992609759103981,06529,0008007002408001,2004,24916,9991505509992,0405,59736,9002,0009951,9983,9005,0001,89539,9992511,69996,49914096,4999,5005,6103,1507,2059,50071,99971,99971,9995,5054,4001,90014,8005,8958,4203,15071,99963971,99913071,99971,99976,0002,7165,5971,1752,0401,3751,3132,2001,1401,6004555203003,2003,1601,12516075903992,0242401201208601,6257001,49915,2003,97596,4991201201206302,750909994903,36990857,9502501,23053,1504993998992,6001,9502896503,00022999211,23019991112409992401524099911902992803252,9004,2004804809995994,000124013,7751,625114,0001,23013201250199912402,2004993201599112401,7992,500160260160240124057012409991130,00032032015,2001132011,2306,90095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095019509509509509509509509509509509509509509509509509509509509509509509509509509509509509509509509509509509509509509509509509509509509509509509509505,7505,7501,23036,9001111,2902,9953,00097085032532090025062,6702402402402403209992402402401202401202403603,000822,17036012508,4203,950948360360206243601,0503602402402401,37024012012095083,9991204654503603101201903993603603602802802802801,375360350320650360510775279991403503603603603603603603603603603603601,66036032599913601,1953703601005103606,9903203202402401,09924012401,98024052402401,49912402401240100801701002401,4002,9963603601,090140599916,5009951,7651,1251,6141,100115701,0001,2994057002901,0993702403603202,4008,4201,0999,9509,950801,5005101,03592545045032025019527,6602,6952753603001503505101802601204252998,8005007505004004001,9501,2501,9501,25080801,2501,9501,5002,7209906996603801494909231,3003,2401,5005,68571,99971,9991,1751,7659503,2401,5006,0551,2608508001,3756003,2401,5006,0556003001201501401001509953,4957504754,4999991,6259909992,49545532070045532018021029,998360360360260909997753603602,5004993203232,7503201401401,26061,4603601,0501502,6206991504,5003601,0003603609991501,6753,7751,6757302901,2204,50012,50064011,9003006,9008095300300804,73036036036036070032023010580903,7505702101,195901,4758752109993202103601,20024090801902804405804,4461643902904551,6259202401,0202403901603201609593002002006,5003602002502,1001,1996909509509509509509509509509509509509509509509509509509509509509509509509501509509509509509509509509509509509509509509909909902859501,1507,4005251,44510,74010,74010,74010,74010,74010,74010,74010,74046010,74010,74010,74010,74010,7403,05010,74010,74036019510,7401,7651,95010,74010,74010,74010,74051036015,2002403603601,27536039984029,0007301,2009991,6001201203701,2302801515993504204,5002103202003205101,950320360317700360700326,9971,3757,5007003993603982,0402402405992403992402402403601,05036029024012012017530,4177201201201431201201204254,3802401203601,76521064,8954,3803603609901,9506,50026090801001,6251003203703603701,3753603504304502753602403609509502902907953603601,40099972012011,65030066030057029,00096030038051,9993,2006034033,99940017051,9992994,2006552991,50015,2008992,3002,40080057029929929929912,5303606995525020,89080,0005001,94119,6001,1751,099370150756,7006991401403503959909754,5501,625200200210991201,1002,9962,6957251,9009001,6994504007991,3136,6502,4606,8502,9952401501508002201,4982402402402402401,0901,0901,0904604603803803503501702,3999593601,26099993601,6902403,7653,3693603603603604603603202402403601,4995703602423273603605103603603,4502,4507009001,76503603201,2004006993203603602992992992992993203605753605991992,6992407,15036099980048,999575775199903608992,8003751402101,7653601401801806903201,0001,7654,2494903604,200775999921099210210992,6001,6251,6002502402403607001,3756402403,5009993609991,4001,0503601,5005001,1003603601,300998,4203602409998,420210320993602403608,4203203203,2504604009,5001001,1001,6255701,0101402909801002804202802808902201403202,2953206903501,1001,4903306551,0803203202992,6001,9502,6008,420100801701009915095553252401,4992109903008016,99911,9993,50029,0006701,4001,0504504502,5509509507659951,6996,99099936029,00060036064,49929099944,68044,6801,31516,50033045561592333046549949913,4501,1501,6582,9981,7654204757993001,1951802,4991,765999895120991,500991889708751,7003904,1501,3501,6909999991,6606,9903903603503993993991,79514014014059927520,8905507,8001151301821,7009,5001,7611,0653604,3951,0804909902,510902202,5003,0001,3501,6908741,0001,0003965,62595015021021026028015,2008996806801,2001,0507002,1992,79960019019015,2004992,5999,9999998997008108504,2001,6902,5001,76536016,50036032032036015,2003601,0807201,0993601,00451,99948,000903603608036036099999924024034,57524024029,0002402403802402,500399160180390180146070080015,20080099928552036032026,0001,2303605559912,50024,9991,35099921219911,8001,0993606003503001995957451051901993,7753601,62530030086019999921015,20015,2001991999502,50024036095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095095012,350993,7001403601,090904,450991,0903606402,5993608006406753206752402,499999924012,50011,90032010,9995207003609991,2504351,49936012012070010,5009,799260700901401401401401993601401409,4007001803202,6952,6953801801009598993601,45016,5001806401,5006502403,4201454,50554,9001199999999991,253901004255703606,0003601,350240214256506557957401109998001209991,5606,05511,400650123701115993601,1851999124,99916,67029,00011,50057569973865064,8955007209993907203203605701,0005983,0003605992,5483956503605201,7993,1991,44599919,49946084020,8901502852602754551,5002,7502,2602,4008101,8501,85017039542539071,9992501883202401,75080080,00064,49916,50016,5003505706603008080994,8501,79958065320,8903604,2494505704255806531,49983,99983,9994257993951751,60064,49912012014458424032048,00045090340150753003004,50024,999908095945552016,50015,999555758003601603603202602601802403954,53011,9993604503606001,3998014099950025033949996,4991,7981441,999475124075099124065012403603202403603202402407002502502501609596,390210210600240240100360500360991803201809999996,0003603201,0001803607403603601401403,7501,3751,0991,0991,0992402402402402402402402403603602402403793606409998105102403502513993991,09965099910010090801009,01036012096,0002001009991002,2461,1202,7951,1609993,8502,5994901,2454001,0994494494495253605203601301003993253,000460115906404991107751951652402603602402402402402402402409992403201809992403605554,53036018032565065599937937019925025064032070024055754,5004494494495251,3759991,7653604,5002502501803201,29920,89015,2007658102502503605708001201204,5302503002501,2305102502503256404,0202402401406991,6301,4901,5003304901,3503504,0002008004501,4001,20075066015057030030054,08063,7206806003401,2004,4991,2001201903201101507546042521210064,99975099959,600901101,5003506709,0001601804,5004,5003551181181181181182,0001,7001,5002,1992401,2331801431206006,05516,99920099993601,7002,9961,0507,46315,2001,27511,90012,5002504903,6009,9009,8001,4901,2003603603603601,0993203603603606708996,9996,9997008634,9501,16032022,8002996,0551902,2461,5005003609755,625240435899555201983201402502502402503902401991996503603201,2309992,75019912099936036032021021021095959,9995253601,5003606001001001988014030036090800999999980802,0001,0998080120801406503,75014,8001401403201,1753603602401,230280360991401401401401401401401402892402403601802403602401,500999999919,370199999550140150240140360905993201006,00011,5001,7008,5001,0991,7652,45012,99920,90034032032016,00032010,50028032019,37028029924070036032036,50019016099916,0003605703604255105,1503,9205,4751,5509991802,50016,0008403203603602402402402502402406,00024057024024024057099240360650997992406501,9983,42012536099924024036030024099993604494492,4992101604201903,600240234999240144551,80026024044,6802971653601,0501,4955201,14016,0001,9958553606501,95025036010,500660995660160455799240240240240904507007007001,000300490250199551501,0007501,0502501605102601401104755519914317038435233621018514317038435233621018514317038435233621018572,0002,69919980016,00027,6604,50013,80029,00035029,00029,0002,28524012,2806,39012,5303,2003504,49916,0001,20029719899992401201201204604,5001,82512012012099086336024014412012012077516,00010,5002751,23038070045099999989976030,00034,55030,6601,0991606,0003506553602,6203603603603203203602,2502,1502,15099917018032016036015,5002501,2005992502,5003,7502503003,7503009,5002502502502501,4901,0501,4905202602606504502003004,5309991,8801,60318094094028512,80099926017055012012012012014457015,30012,5302852,49028526033026028526070049,4001,2301,23013,7507,0602408501,2001439909006,00051044980180805557018036051099993605705702996,70019,3701,050260320320320400425993307756401102507757502504809902506406409051015036039025025025028512,5303201,09984919,3703002503001,6991,55065025024036036099320160,0003603601,375143,99819,37071,99920,90038039,99938,74039,9999903608704603608,4202,29988,7701501506,90084912,5301,55036548,0006,0551,2301,69010,5003001201,2993609998741759993201501803002,2802,3107002403,49946099999801604501502002803,99910,5001,0509999994493994753502201,0509952752,9961,9501,49925016,0002,00012012095047528012012012,53029,00090801202731027,1503,1033,3792,9951996,90099995204551401,4301,0998015,99921,50011,90014016,50014024036032015,20012025054,9002,0402609016514016516525099162,6202,45020820842516,0002,450360250250993602502502503203202502503602502506,50064096,499250399250320250300350360250180640250250640325120360320799250360360500950969615036032036072,36083,9996401502501606406401803003603603603,90033,99918032099901691702203205,3502817861,25329920,90036010,500360250640360250250992506402506402502503603608292607003601201206406401,2308424491,5095001,3753,4992503604,2127,90075520640250993402503602503603201201206,400120120120120120120120120120120120120120599991201,815991,3751,2749999842991,3753202601,2304252,2201,5601,6209505701,230992802,5004004554553603601,9503603602,15016,000360120120803608080802,50080360360807983952,5004,6832502509992504502851,2005701806904,2493,2091,5517,4501,3505752,1992,4955,6405,6401,5002,4003605705702502,2912,4442,2918424,20825039911010,5002,99536068044,6809999999999999993603601433601,9908504904903707601,23036016,00027049516516,0009992,5502101503,7007502,15219,4993172002002,0008994554152851,420599653,78949,4004,02013,30028155270140140901501,2308,4201,2304603303,4651,6001

In [32]:
pt

np.float64(3710606594.1299996)

In [5]:
df['Customer ID'].unique().sum()

np.float64(nan)

In [6]:
df['Customer ID'].drop_duplicates().sum()

np.float64(6650100801.0)

In [7]:
df['Customer ID'].sum()

np.float64(26765149520.0)

In [9]:
df['item_id'].duplicated().sum()

np.int64(0)

In [10]:
df

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
0,211131,complete,7/1/2016,kreations_YI 06-L,1950.0,1,1950.0,100147443,Women's Fashion,\N,...,cod,7/1/2016,#REF!,"1,950",2016,7,2016-7,Jul-16,FY17,1.0
1,211133,canceled,7/1/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.0,1,240.0,100147444,Beauty & Grooming,\N,...,cod,7/1/2016,Gross,240,2016,7,2016-7,Jul-16,FY17,2.0
2,211134,canceled,7/1/2016,Ego_UP0017-999-MR0,2450.0,1,2450.0,100147445,Women's Fashion,\N,...,cod,7/1/2016,Gross,"2,450",2016,7,2016-7,Jul-16,FY17,3.0
3,211135,complete,7/1/2016,kcc_krone deal,360.0,1,60.0,100147446,Beauty & Grooming,R-FSD-52352,...,cod,7/1/2016,Net,360,2016,7,2016-7,Jul-16,FY17,4.0
4,211136,order_refunded,7/1/2016,BK7010400AG,555.0,2,1110.0,100147447,Soghaat,\N,...,cod,7/1/2016,Valid,"1,110",2016,7,2016-7,Jul-16,FY17,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584519,905204,cod,8/28/2018,WOFSCE5AE00357AECDE,699.0,1,849.0,100562385,Women's Fashion,NaN,...,cod,8/28/2018,Valid,699,2018,8,2018-8,Aug-18,FY19,115320.0
584520,905205,processing,8/28/2018,MATHUA5AF70A7D1E50A,35599.0,1,35899.0,100562386,Mobiles & Tablets,NaN,...,bankalfalah,8/28/2018,Gross,"35,599",2018,8,2018-8,Aug-18,FY19,115326.0
584521,905206,processing,8/28/2018,MATSAM5B6D7208C6D30,129999.0,2,652178.0,100562387,Mobiles & Tablets,NaN,...,bankalfalah,8/28/2018,Gross,"259,998",2018,8,2018-7,Aug-18,FY19,113474.0
584522,905207,processing,8/28/2018,MATSAM5B1509B4696EA,87300.0,2,652178.0,100562387,Mobiles & Tablets,NaN,...,bankalfalah,8/28/2018,Gross,"174,600",2018,8,2018-7,Aug-18,FY19,113474.0
584523,905208,processing,8/28/2018,MATSAM5B10F91A9B6AB,108640.0,2,652178.0,100562387,Mobiles & Tablets,NaN,...,bankalfalah,8/28/2018,Gross,"217,280",2018,8,2018-7,Aug-18,FY19,113474.0

In [11]:
df['grand_total'].mean()

np.float64(8530.618570950894)